#1 Inverse. All the collections made by an Actor


PREFIX  org:  <http://example.com/org/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  wdt:  <http://www.wikidata.org/prop/direct/>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  wd:   <http://www.wikidata.org/entity/>
PREFIX  crm:  <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?value WHERE {
  ?subject rdf:type crm:E39_Actor;
    (^crm:P14_carried_out_by/^crm:P108i_was_produced_by) ?collection.
  ?collection rdf:type crm:E78_Collection;
    (crm:P1_is_identified_by/rdfs:label) ?value.
}
